spring:
  datasource:
    druid:
      url:  jdbc:mysql://120.26.176.128:3306/social_commerce?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      driver-class-name:  com.mysql.cj.jdbc.Driver
      username:  sc12345
      password:  sc12345
      initial-size:  10
      max-active:  50
      min-idle:  10
      max-wait:  60000
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query:  SELECT 1 FROM DUAL
      test-on-borrow:  false
      test-on-return:  false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
      filters:  stat,wall
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: social-commerce-gateway

server:
  port: 8002

# Eureka相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
  instance:
    ipaddress: localhost
    lease-renewal-interval-in-seconds: 10      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 60  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
zuul:
  routes:
#    wx:
#      path: /wx/**
#      url: forward:/wx
    admin:
      path: /admin/**
      url: forward:/admin
        # 针对某个服务的配置，可自定义
    demo-order:
      path: /admin/storage/**
      serviceId: file-upload-service
      stripPrefix: true
          # 不向后端服务传递的敏感头信息
#          sensitiveHeaders: Cookie,Set-Cookie,Authorization
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000




